require("__khaoscarbon__.prototypes.categories.recipe-category")

require("__khaoscarbon__.prototypes.particles.flake-graphite-particle")
require("__khaoscarbon__.prototypes.particles.rough-diamond-particle")
require("__khaoscarbon__.prototypes.entity.resources.flake-graphite")
require("__khaoscarbon__.prototypes.entity.resources.rough-diamond")

require("__khaoscarbon__.prototypes.item.flake-graphite")
require("__khaoscarbon__.prototypes.item.rough-diamond")
require("__khaoscarbon__.prototypes.item.graphite")
require("__khaoscarbon__.prototypes.item.diamond")
require("__khaoscarbon__.prototypes.item.graphene")
require("__khaoscarbon__.prototypes.item.fullerenes")
require("__khaoscarbon__.prototypes.item.nanotubes")
require("__khaoscarbon__.prototypes.item.carbon-black")
require("__khaoscarbon__.prototypes.item.crucible")

require("__khaoscarbon__.prototypes.recipe.graphite")
require("__khaoscarbon__.prototypes.recipe.synthetic-diamond")
require("__khaoscarbon__.prototypes.recipe.diamond")
require("__khaoscarbon__.prototypes.recipe.graphene")
require("__khaoscarbon__.prototypes.recipe.fullerenes")
require("__khaoscarbon__.prototypes.recipe.nanotubes")
require("__khaoscarbon__.prototypes.recipe.carbon-black")
require("__khaoscarbon__.prototypes.recipe.graphite-carbon-black")
require("__khaoscarbon__.prototypes.recipe.crucible")

require("__khaoscarbon__.prototypes.technology.graphite-processing")
require("__khaoscarbon__.prototypes.technology.diamond-processing")
require("__khaoscarbon__.prototypes.technology.graphene")
require("__khaoscarbon__.prototypes.technology.fullerenes")
require("__khaoscarbon__.prototypes.technology.nanotubes")

require("__khaoscarbon__.prototypes.compat.base")
require("__khaoscarbon__.prototypes.compat.basic-crusher")
require("__khaoscarbon__.prototypes.compat.khaosfoundry")
