name: QA // Release

on:
  push:
    branches:
      - "0.x"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  qa:
    name: QA
    uses: QuingKhaos/khaosci/.github/workflows/qa.yml@4b3a9b2518e365d5e5d0a9fa0bc65ad8bd7c8c63

  release:
    name: Release mod
    uses: QuingKhaos/khaosci/.github/workflows/release.yml@4b3a9b2518e365d5e5d0a9fa0bc65ad8bd7c8c63
    if: (github.event_name == 'push' && contains(github.event.head_commit.message, 'chore(release):')) || github.event_name == 'workflow_dispatch'
    needs: [qa]
    with:
      lfs: true
      mod-folder: .
      skip-update-details: ${{ github.ref_name != '0.x' }}
    secrets:
      factorio-api-key: ${{ secrets.FACTORIO_API_KEY }}
