name: Quality Assurance

on:
  pull_request:
    branches:
      - "1.x"
      - "2.x"

jobs:
  qa:
    name: QA
    uses: QuingKhaos/khaosci/.github/workflows/qa.yml@4b3a9b2518e365d5e5d0a9fa0bc65ad8bd7c8c63
